  version: '3.7'
  services:
    mysql:
      image: mysql:8.0
      volumes:
        - mysql-data:/var/lib/mysql
        # 初回起動時にテストDBを作成する
        - ./docker/entrypoint:/docker-entrypoint-initdb.d
      environment:
        MYSQL_DATABASE: database
        MYSQL_ROOT_PASSWORD: password
        TZ: Asia/Tokyo
      ports:
        - '3306:3306'

  volumes:
    mysql-data:
      driver: local
